server:
  port: 8080
  error:
    include-message: always
    include-binding-error: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timesphere
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


app:
  jwt-secret: 6bc4b66bb91521758a881387561d819f5bf6609597e51d4cc110944f01051695b4781a2381584d900315da8121d4f19cf8dbed662ab8ee4977a6c6b3bbd353e5
#  jwt-secret: ${JWT_SECRET:default_secret_value}
  jwt-expiration-milliseconds: 3600000